# Generated by Django 3.0.7 on 2020-08-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discipline",
            name="slug",
            field=models.SlugField(
                help_text="The URL fragment uniquely identifying the discipline.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="duration",
            name="is_timed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the duration can be interpreted as a time range.",
            ),
        ),
        migrations.AlterField(
            model_name="maneuver", name="slug", field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="range",
            name="is_numeric",
            field=models.BooleanField(
                default=False,
                help_text="Whether the range can be feasibly interpreted as a number.",
            ),
        ),
    ]
