# Generated by Django 3.0.7 on 2020-08-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search_engine", "0002_auto_20200810_2146"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maneuver", old_name="type", new_name="maneuver_type",
        ),
    ]
