# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_auto_20150126_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maneuver',
            name='descriptor',
            field=models.ManyToManyField(blank=True, to='search_engine.Descriptor'),
        ),
    ]
